# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_hour', models.IntegerField(default=-1)),
                ('end_hour', models.IntegerField(default=-1)),
                ('date', models.DateField(db_index=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('iso_year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('thing', models.CharField(max_length=1024)),
                ('time_cost_min', models.IntegerField()),
                ('level', models.IntegerField(default=-1)),
                ('category', models.CharField(max_length=1024)),
                ('project', models.CharField(max_length=1024)),
            ],
        ),
    ]
